
[character]
success_symbol = "[➜ ](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[python]
disabled = true

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[directory]
truncation_length = 8
truncation_symbol = "…/"

