
format = "$character"
right_format = """$all"""

[character]
success_symbol = "[ᚠᛒᛒ ](bold green)[᛫](fg:240)"
error_symbol = "[ᛖᚱᚱ ](bold fg:88)[᛫](fg:196)"
vicmd_symbol = "[ᚹᛁ ᛫](bold green)"

[python]
disabled = true

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[directory]
truncation_length = 6
truncation_symbol = "…/"

[nodejs]
format = '[](bold fg:41) via $version'
